M48
; DRILL file {KiCad 9.0.3} date 2025-10-01T09:47:46-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-01T09:47:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X46.65Y-114.35
X85.35Y-114.35
T2
X44.0Y-123.5
X45.5Y-74.5
X111.0Y-138.0
M30
